#!/bin/bash
#root_dir="."
source "./../../env/var.sh"

rm "$module_data_dir/*"
rm "$consumer_data_dir/*"

#module_type='text'
task=$1

#task_type=`sed {1q} $task`

#echo $module_type
#echo $task_type

#[ $task_type == $module_type ] && (exit 1)

#data=`sed -n 2p $task`

#в папке out каждого модуля
task_count=0
while [ 1 ]; do

for data in $(ls "$consumer_data_dir"); do
	data_file="$consumer_data_dir/$data"
	let task_count++
	./driver "$data_file"
	rm "$data_file"
done
echo "tasks consumed: $task_count"
sleep 0.1s
done
#забрать последние данные, добавить к ним описание
#положить в очередь, удалить данные 

