#!/bin/bash
# http://ru.festivalspeaker.wikia.com
data_file="$1"
tmp_dir="tmp"
wav_file="./$tmp_dir/$data_file.wav"
text=`cat "$data_file"`
echo "$text" | text2wave -o "$wav_file" -eval "(voice_msu_ru_nsh_clunits)"
aplay "$wav_file" > /dev/null 2>&1
rm "$wav_file"
exit 0
