#!/bin/bash
readonly root_dir="."
readonly modules_dir="$root_dir/modules"
readonly producer_data_dir="out"
readonly consumer_data_dir="in"
readonly module_data_dir="tmp"
readonly qeue_dir="$root_dir/qeue"
readonly qeue_task_dir="$qeue_dir/task"
readonly qeue_data_dir="$qeue_dir/data"
readonly producer_infofile="producer.info"
readonly consumer_infofile="consumer.info"
readonly task_prefix="task"
readonly task_template="$qeue_task_dir/$task_prefix*"
readonly producers_list="$modules_dir/producers_active"
readonly consumers_list="$modules_dir/consumers_active"
